### ISSUE TITLE
Fails on extract-function

### ISSUE THREAD

**Issue by TheoAndersen** [magnars/js2-refactor.el#10]
When i extract function it changes the marked text to the function calls, but does'nt create the function.

Error:
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  js2-node-abs-pos(nil)
  js2r--extract-fn("sdfkjl" #[nil "\300 ?\205\f^@\301\302\303!!b\207" [js2r--looking-at$
  js2r-extract-function("sdfkjl")
  call-interactively(js2r-extract-function nil nil)

This should be a pretty basic emacs 24.2.1 install with only js2-mode and js2-refactor installed via Melpa

**Comment by MoHKale** [comment]
I'm having a similair sort of issue. When you try to extract something from the root of a file into a function, an error `helm-M-x: Wrong type argument: js2-node, nil` is thrown. I believe it's because js2-refactor by default creates a new method at a higher scope than the one you wrapped and extracted, but at the root of a file, there's no higher point it can extract to. If I run the same operation from within a method, it extracts the marked region to the root.

Let me explain what I mean, say I have a file like this:

```javascript
var buttons = {
    'reset': document.getElementById("reset"),
    'confuse': document.getElementById("confuse"),
    'jump': document.getElementById("jump"),
    'wiggleEars' : document.getElementById("wiggle-ears")
};
```

if I mark this entire region and run `js2r-extract-function` with a function name foo, I'll be left with

```javascript
var buttons = this.foo(document, getElementById);
```

but the marked selection isn't actually moved into a function named `foo`. Now if I wrap the initial expression in a function.

```javascript
function foo() {
    var buttons = {
        'reset'      : document.getElementById("reset"),
        'confuse'    : document.getElementById("confuse"),
        'jump'       : document.getElementById("jump"),
        'wiggleEars' : document.getElementById("wiggle-ears")
    };
}
```

now if I do so again, marking the body of the function foo.

```javascript
function bar() {
    var buttons = {
        'reset'      : document.getElementById("reset"),
        'confuse'    : document.getElementById("confuse"),
        'jump'       : document.getElementById("jump"),
        'wiggleEars' : document.getElementById("wiggle-ears")
    };
}

function foo() {
    bar();
}
```

you get the expected behaviour. granted this is kind of an absurd example, but this is whats happening for me.

**Comment by MoHKale** [comment]
maybe instead of throwing a somewhat ambiguous error message when trying to do this, we should instead print something like "cannot slurp outside of a nested construct" or something like that.
